### ISSUE TITLE
Ionic Deploy fails to extract snapshot on Android

### ISSUE THREAD

**Issue by johnellmore** [driftyco/ionic-cloud#110]
When running my app on Android, I'm getting an error when trying to load in a new snapshot from Ionic Deploy.

As shown by logcat in Android Studio:

```
...
12-01 17:08:26.240 510-547/APP_ID I/IONIC.DEPLOY.DOWNLOAD: Progress: 99%
12-01 17:08:26.243 510-547/APP_ID I/IONIC.DEPLOY.DOWNLOAD: Progress: 100%
12-01 17:08:26.250 510-510/APP_ID I/chromium: [INFO:CONSOLE(6)] "Ionic Deploy: download complete", source: file:///android_asset/www/lib/ionic.cloud.min.js (6)
12-01 17:08:26.272 510-510/APP_ID I/chromium: [INFO:CONSOLE(26794)] "TypeError: Cannot read property 'emitter' of undefined
                                                                                 at e.extract (file:///android_asset/www/lib/ionic.cloud.min.js:6:24131)
                                                                                 at processQueue (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:29127:28)
                                                                                 at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:29143:27
                                                                                 at Scope.$eval (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:30395:28)
                                                                                 at Scope.$digest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:30211:31)
                                                                                 at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:30434:26
                                                                                 at completeOutstandingRequest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:19194:10)
                                                                                 at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:19470:7", source: file:///android_asset/www/lib/ionic/js/ionic.bundle.js (26794)
```

This error seems to be originating from this line in the Ionic Cloud client:
https://github.com/driftyco/ionic-cloud/blob/master/src/deploy/deploy.ts#L155

Here's how I'm invoking the deploy process:

```javascript
angular.module('app.controllers', ['ionic.cloud'])
.controller('AppCtrl', function( ... $rootScope, ... $ionicDeploy) {

    $rootScope.$on('appAuthenticated', function (event, settingsData) {

        // check for new deploy snapshots
        $ionicDeploy.check().then(function(snapshotAvailable) {
            if (snapshotAvailable) {
                return $ionicDeploy.download()
                    .then($ionicDeploy.extract);
            }
        });

    });

})
```

On iOS, the Ionic Deploy works flawlessly. This issue occurs in my testing on Android 4.4, 5.0, and 6.0.

I'm using:
- Ionic v1.3.1 (and thus Angular 1.5.3)
- Ionic Cloud client v0.14.0
- ionic-plugin-deploy v0.6.5 (Cordova plugin)

Any help will be greatly appreciated!

**Comment by ericb** [comment]
@johnellmore The fact that it's working on iOS but not Android makes me think that this is actually an outdated dependency being used when you run the build for Android. Are you able to provide a test project we can build and run?

**Comment by johnellmore** [comment]
Unfortunately, I can't provide the project, as it's a private project for a client. I can possibly provide certain files, though; are there specific files that you'd like to see? My employer is okay granting outside access to the codebase, but would require some legal paperwork first. So I'd love to avoid that complexity if possible :)

Or if that's too tedious, do you have any suggestions for where I can start troubleshooting?

I appreciate your help!

**Comment by ericb** [comment]
@johnellmore One thing you could do is to print out the version of the cloud client from within your app code. If it's running an out of date version that would show an older version instead of your latest version you may or may not have installed. Here is a reference to the [code](https://github.com/driftyco/ionic-cloud/blob/master/src/core.ts#L55) but I'm blanking on the usage off the top of my head. @dwieeb can you provide a usage example?

**Comment by dwieeb** [comment]
```javacript
.controller('AppCtrl', function( ... $rootScope, ... $ionicCloud) {
    console.log($ionicCloud.version);
})
