### ISSUE TITLE
Error building my ionic 2 project $cordova build android

### ISSUE THREAD

**Issue by zenismaharjan** [driftyco/ionic-cloud#124]
Not Being able to build my ionic 2 projects, gives the following error:

**A problem occurred configuring root project 'android'.
Failed to find Platform SDK with path: platforms;android-24**

```
>  $cordova build android
> ANDROID_HOME=/home/zenis/Android/Sdk
> JAVA_HOME=/usr/lib/jvm/java-8-oracle
> Subproject Path: CordovaLib
> Could not initialize analytics, treating as opt-out.
> java.io.FileNotFoundException: /home/zenis/.android/analytics.settings (Permission denied)
> 	at java.io.RandomAccessFile.open0(Native Method)
> 	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
> 	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
> 	at com.android.tools.analytics.AnalyticsSettings.saveSettings(AnalyticsSettings.java:266)
> 	at com.android.tools.analytics.AnalyticsSettings.createNewAnalyticsSettings(AnalyticsSettings.java:202)
> 	at com.android.builder.profile.ProcessRecorderFactory.initializeAnalytics(ProcessRecorderFactory.java:196)
> 	at com.android.builder.profile.ProcessRecorderFactory.get(ProcessRecorderFactory.java:220)
> 	at com.android.builder.profile.ProcessRecorderFactory.initialize(ProcessRecorderFactory.java:122)
> 	at com.android.build.gradle.internal.profile.ProfilerInitializer.init(ProfilerInitializer.java:66)
> 	at com.android.build.gradle.BasePlugin.apply(BasePlugin.java:310)
> 	at com.android.build.gradle.AppPlugin.apply(AppPlugin.java:75)
> 	at com.android.build.gradle.AppPlugin.apply(AppPlugin.java:41)
> 	at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
> 	at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
> 	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:137)
> 	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:112)
> 	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:113)
> 	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:36)
> 	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:80)
> 	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:136)
> 	at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:46)
> 	at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.java:34)
> 	at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
> 	at build_9ur5z8ra8urz0rnewezr438tr.run(/home/zenis/ionic/schoolApp3/platforms/android/build.gradle:20)
> 	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
> 	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:177)
> 	at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
> 	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:182)
> 	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:38)
> 	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:25)
> 	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
> 	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
> 	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:540)
> 	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:93)
> 	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
> 	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
> 	at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:124)
> 	at org.gradle.internal.Factories$1.create(Factories.java:22)
> 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
> 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
> 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:121)
> 	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
> 	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
> 	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
> 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
> 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
> 	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
> 	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
> 	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
> 	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
> 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
> 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
> 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
> 	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
> 	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
> 	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
> 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
> 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
> 	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
> 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
> 	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
> 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
> 	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
> 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
> 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
> 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
> 	at org.gradle.util.Swapper.swap(Swapper.java:38)
> 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
> 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
> 	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
> 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
> 	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
> 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
> 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
> 	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
> 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
> 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
> 	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
> 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
> 	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
> 	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:237)
> 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
> 	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> java.nio.file.NoSuchFileException: /home/zenis/.android/cache/sdkbin-1_b735609c-repository2-1_xml
> Failed to download any source lists!
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring root project 'android'.
> > Failed to find Platform SDK with path: platforms;android-24
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
```

**Comment by piotrowski** [comment]
Hey, your issue doesn't seem to be connected to ionic-cloud in any way. Please post your problem at the Ionic Forum at https://forum.ionicframework.com/ People there will try to debug your issue with you.
