### ISSUE TITLE
Can't login with InAppBrowser flow. at InstagramAuthType.AuthType.inAppBrowserFlow on desktop

### ISSUE THREAD

**Issue by nicksmithr** [driftyco/ionic-cloud#136]
Not a major issue, but would be nice to be able to log in on browser instead of having to run on device in production.

When running ionic serve, this error results (of course, because there's no InAppBrowser on desktop), all works fine on mobile.
```
Error: Uncaught (in promise): Error: Cordova is missing--can't login with InAppBrowser flow.
Error: Cordova is missing--can't login with InAppBrowser flow.
    at InstagramAuthType.AuthType.inAppBrowserFlow (http://localhost:8100/build/main.js:57068:36)
    at InstagramAuthType.authenticate (http://localhost:8100/build/main.js:57523:21)
    at Auth.login (http://localhost:8100/build/main.js:56948:24)
    at LoginPage.userAuth (http://localhost:8100/build/main.js:56498:19)
    at CompiledTemplate.proxyViewClass.View_LoginPage0.handleEvent_12 (/AppModule/LoginPage/component.ngfactory.js:153:34)
    at CompiledTemplate.proxyViewClass.<anonymous> (http://localhost:8100/build/main.js:99974:37)
    at HTMLButtonElement.<anonymous> (http://localhost:8100/build/main.js:39174:36)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9723)
    at Object.onInvokeTask (http://localhost:8100/build/main.js:37222:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9659)
    at s (http://localhost:8100/build/polyfills.js:3:4211)
    at s (http://localhost:8100/build/polyfills.js:3:4034)
    at http://localhost:8100/build/polyfills.js:3:4574
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9723)
    at Object.onInvokeTask (http://localhost:8100/build/main.js:37222:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9659)
    at e.runTask (http://localhost:8100/build/polyfills.js:3:7083)
    at i (http://localhost:8100/build/polyfills.js:3:3671)
    at HTMLButtonElement.invoke (http://localhost:8100/build/polyfills.js:3:10876)
```

**Comment by diegocatalao** [comment]
+1

**Comment by vrajroham** [comment]
@nicksmithr Did you managed to solved it?
